export const CODING_PROFILES = {
  leetcode: {
    handle: "KALLUL",
    profileUrl: "https://leetcode.com/u/KALLUL/",
    totalSolved: 150,
    easy: { solved: 65, total: 830 },
    medium: { solved: 72, total: 1740 },
    hard: { solved: 13, total: 740 },
    contestRating: 1520,
    topPercentage: "18%",
    streak: 12,
    recentSubmissions: [
      { title: "Two Sum", difficulty: "Easy", time: "2h ago", status: "Accepted" },
      { title: "Longest Substring Without Repeating Characters", difficulty: "Medium", time: "5h ago", status: "Accepted" },
      { title: "LRU Cache", difficulty: "Medium", time: "1d ago", status: "Accepted" },
      { title: "Merge K Sorted Lists", difficulty: "Hard", time: "2d ago", status: "Accepted" },
      { title: "Valid Parentheses", difficulty: "Easy", time: "3d ago", status: "Accepted" },
    ],
  },
  codeforces: {
    handle: "KALLUL",
    profileUrl: "https://codeforces.com/profile/KALLUL",
    rating: 1186,
    maxRating: 1209,
    rank: "Newbie",
    maxRank: "Pupil",
    contribution: 0,
    organization: "NIT Silchar",
    totalContests: 34,
    recentContests: [
      { name: "Educational Codeforces Round 188", rank: 7421, ratingChange: -20 },
      { name: "Codeforces Round 1086 (Div. 2)", rank: 5504, ratingChange: +29 },
      { name: "Educational Codeforces Round 187", rank: 5532, ratingChange: +15 },
      { name: "Codeforces Round 1080 (Div. 3)", rank: 7834, ratingChange: +8 },
      { name: "Codeforces Round 1079 (Div. 2)", rank: 4950, ratingChange: +78 },
      { name: "Codeforces Round 1078 (Div. 2)", rank: 10385, ratingChange: -41 },
    ],
  },
};
