import { Project, Experience, Activity } from "./types";

export const PROJECTS: Project[] = [
  {
    id: 1,
    name: "Posua-26-Website",
    description: "The official website for Posua 2026, featuring event information and cultural showcases of NIT Silchar.",
    language: "TypeScript",
    languageColor: "#3178c6",
    stars: 0,
    forks: 0,
    updatedAt: "today",
    topics: ["nextjs", "typescript", "tailwindcss", "framer-motion"],
    pinned: true,
    status: "ongoing",
  },
  {
    id: 2,
    name: "Incand26",
    description: "Modern web portal for Incandescence '26 built with Next.js, typescript, tailwindcss and Cloudinary for high-performance media handling.",
    language: "TypeScript",
    languageColor: "#3178c6",
    stars: 0,
    forks: 0,
    updatedAt: "Feb 2026",
    topics: ["nextjs", "typescript", "cloudinary", "tailwindcss"],
    pinned: true,
    status: "completed",
    link: "https://github.com/gdsc-nits-org/Incand26.git",
  },
  {
    id: 5,
    name: "Padho.AI",
    description: "An AI-powered adaptive learning system that adjusts quiz difficulty using Scikit-Learn and provides insights via Google Gemini.",
    language: "TypeScript",
    languageColor: "#3178c6",
    stars: 0,
    forks: 0,
    updatedAt: "Jan 2026",
    topics: ["React-js", "javascript", "express-js", "node-js", "tailwindcss", "fastapi", "machine-learning", "gemini-api"],
    pinned: true,
    status: "completed",
    link: "https://github.com/kallulgogoi/TLE.git"
  },
  {
    id: 3,
    name: "CSS-Olympics-App",
    description: "Full-stack mobile app for NIT Silchar's CS Society Olympics. Features event registration and match schedules for 250+ users.",
    language: "JavaScript",
    languageColor: "#f1e05a",
    stars: 0,
    forks: 0,
    updatedAt: "Jan 2026",
    topics: ["react-native", "typescript", "expo", "mongodb", "express-js", "cloudinary", "react-js", "tailwind-css", "google-auth", "native-wind", "node-js"],
    pinned: true,
    status: "completed",
    link: "https://github.com/kallulgogoi/CSS-APP-FRONTEND.git"
  },
  {
    id: 4,
    name: "AI-Multiplayer-Quiz",
    description: "Real-time multiplayer quiz platform with Socket.io gameplay and AI-based question generation via Gemini API.",
    language: "JavaScript",
    languageColor: "#f1e05a",
    stars: 0,
    forks: 0,
    updatedAt: "Dec 2025",
    topics: ["React-js", "Tailwind-css", "Express-js", "Node-js", "MongoDb", "socket-io", "google-oauth", "cloudinary"],
    pinned: true,
    status: "completed",
    link: "https://github.com/kallulgogoi/quiz-project-mern.git"
  },
  {
    id: 6,
    name: "CSS-Official-2025",
    description: "The primary digital presence for the Computer Science Society at NIT Silchar, utilizing Supabase for backend services.",
    language: "JavaScript",
    languageColor: "#f1e05a",
    stars: 0,
    forks: 0,
    updatedAt: "Sept 2025",
    topics: ["react", "tailwind-css", "supabase"],
    pinned: true,
    status: "completed",
    link: "https://github.com/ComputerScienceSoceityNITS/css-official-website-2025-26.git"
  },
  {
    id: 7,
    name: "Expense-Tracker",
    description: "A full-stack financial tool for tracking income and expenses with real-time CRUD operations and data visualization.",
    language: "JavaScript",
    languageColor: "#f1e05a",
    stars: 0,
    forks: 0,
    updatedAt: "July 2025",
    topics: ["React-js", "Tailwind-css", "Express-js", "Node-js", "MongoDb", "Rechart", "cloudinary"],
    pinned: false,
    status: "completed",
    link: "https://github.com/kallulgogoi/Expense-tracker.git"
  },
  {
    id: 20,
    name: "Portfolio 1",
    description: "A modern, responsive personal portfolio featuring high-performance UI animations. Built with React.js and Tailwind CSS, leveraging Framer Motion for buttery-smooth transitions and an interactive user experience.",
    language: "JavaScript",
    languageColor: "#f1e05a",
    stars: 0,
    forks: 0,
    updatedAt: "Sept 2025",
    topics: ["react", "tailwindcss", "framer-motion"],
    pinned: false,
    status: "completed",
    link: "https://github.com/kallulgogoi/Portfolio.git"
  },
  {
    id: 8,
    name: "Photo-to-URL",
    description: "A utility tool that generates accessible URLs for images using Cloudinary integration and a clean JS interface.",
    language: "HTML",
    languageColor: "#e34f26",
    stars: 0,
    forks: 0,
    updatedAt: "June 2025",
    topics: ["HTML", "CSS", "javascript", "cloudinary"],
    pinned: false,
    status: "completed",
    link: "https://github.com/kallulgogoi/Photo_to_URL.git"
  },
  {
    id: 9,
    name: "Technoesis 2025 Official Website",
    description: "UI/UX design for Technoesis 2025 official website.",
    language: "Figma",
    languageColor: "#F24E1E",
    stars: 0,
    forks: 0,
    updatedAt: "recently",
    topics: ["ui/ux", "figma", "design"],
    pinned: false,
    status: "completed",
    link: "https://www.figma.com/design/4VxElsyCeNLkDIvmjyVRdm/Tecno25UIUX?node-id=0-1&t=okx0aU3YZgefdehN-1",
  },
  {
    id: 10,
    name: "Personal Portfolio",
    description: "Design mockups and UI considerations for a personal portfolio(Abacus Css UI/UX Hacks)",
    language: "Figma",
    languageColor: "#F24E1E",
    stars: 0,
    forks: 0,
    updatedAt: "recently",
    topics: ["ui/ux", "figma", "portfolio"],
    pinned: false,
    status: "completed",
    link: "https://www.figma.com/design/2I7uTYryO4Pq3Xnl6C2J8b/CSS-UI-UX-HACKATHON?m=auto&t=9nN3VIdNXEPA067J-6",
  },
  {
    id: 11,
    name: "Personal Portfolio 2",
    description: "Alternative UI/UX design version for personal portfolio presence.",
    language: "Figma",
    languageColor: "#F24E1E",
    stars: 0,
    forks: 0,
    updatedAt: "recently",
    topics: ["ui/ux", "figma", "portfolio"],
    pinned: false,
    status: "completed",
    link: "https://www.figma.com/design/xSJZXTkt7J1ykm6k8F1Mfm/Untitled?m=auto&t=9nN3VIdNXEPA067J-6",
  },
  {
    id: 12,
    name: "Valentine Theme App",
    description: "A fun and engaging UI/UX design for a Valentine-themed application.",
    language: "Figma",
    languageColor: "#F24E1E",
    stars: 0,
    forks: 0,
    updatedAt: "recently",
    topics: ["ui/ux", "figma", "app-design"],
    pinned: false,
    status: "completed",
    link: "https://www.figma.com/design/YwMvYJw2tLeLfkY6N64sF1/Valentine_app_GDGC_Project-_Main_File?m=auto&t=9nN3VIdNXEPA067J-6",
  },
  {
    id: 13,
    name: "Semester Project Resource App UI",
    description: "Application design for managing formatting, resources, and templates for semester projects.",
    language: "Figma",
    languageColor: "#F24E1E",
    stars: 0,
    forks: 0,
    updatedAt: "recently",
    topics: ["ui/ux", "figma", "education"],
    pinned: false,
    status: "completed",
    link: "https://www.figma.com/design/S1o8tn5UKCWjfa4RZu4u5v/Semester-resources-project?m=auto&t=9nN3VIdNXEPA067J-6",
  },
  {
    id: 14,
    name: "UI/UX ECS Hacks",
    description: "Hackathon project focusing heavily on creating intuitive UI and robust UX flows.",
    language: "Figma",
    languageColor: "#F24E1E",
    stars: 0,
    forks: 0,
    updatedAt: "recently",
    topics: ["ui/ux", "figma", "hackathon"],
    pinned: false,
    status: "completed",
    link: "https://www.figma.com/design/DnwCeFpzdLTZNyt6TWPBCu/UI-UX-ECS-HACKS?node-id=0-1&t=ARVCPlcGBEPdLfVH-1",
  },
];


export const ACTIVITIES: Activity[] = [
  { id: 1, type: "commit", description: "Pushed 4 commits to portfolio-os", date: "today" },
  { id: 2, type: "star", description: "Starred vercel/next.js", date: "yesterday" },
  { id: 3, type: "pr", description: "Opened PR #42 in ai-chat-interface", date: "2 days ago" },
  { id: 4, type: "issue", description: "Opened issue on markdown-editor", date: "3 days ago" },
  { id: 5, type: "commit", description: "Pushed 12 commits to e-commerce-platform", date: "1 week ago" },
  { id: 6, type: "fork", description: "Forked tailwindlabs/tailwindcss", date: "1 week ago" },
];
function seededRandom(seed: number) {
  const x = Math.sin(seed) * 10000;
  return x - Math.floor(x);
}

export const CONTRIBUTION_DATA: number[][] = Array.from({ length: 52 }, (_, wi) =>
  Array.from({ length: 7 }, (_, di) => {
    const r = seededRandom(wi * 7 + di + 1);
    return r > 0.3 ? Math.floor(seededRandom(wi * 7 + di + 100) * 4) + 1 : 0;
  })
);

export const EXPERIENCES = [
  {
    id: 1,
    role: "Junior Moderator",
    company: "Coding Club, NIT Silchar",
    period: "2025 Aug - Present",
    description: "Contributing as a junior moderator, managing events, coding sessions, and helping peers enhance their coding skills.",
  },
  {
    id: 2,
    role: "Junior UI/UX Developer",
    company: "Google Developer Groups Club, NIT Silchar",
    period: "2025 Aug - Present",
    description: "Designing and prototyping modern UI/UX solutions, collaborating with developers to build impactful projects.",
  },
  {
    id: 3,
    role: "Web Wing Member",
    company: "Computer Science Society, NIT Silchar",
    period: "2025 Aug - Present",
    description: "Developing web-based solutions and contributing to society-led projects, enhancing technical exposure and collaboration.",
  },
];

export const EDUCATIONS = [
  {
    id: 1,
    degree: "Bachelor of Technology - BTech",
    school: "NIT Silchar",
    period: "Aug 2024 - Present",
    description: "I am a 2nd year B.Tech student of Computer Science and Engineering branch at NIT Silchar. I have completed my 3rd sem with a SGPA of 8.92.",
    marks: "CGPA: 8.42",
    status: "Present",
  },
  {
    id: 2,
    degree: "Higher Secondary, Science Stream (PCM)",
    school: "Sadiya College",
    period: "July 2022 - Jan 2024",
    description: "Completed my higher secondary education with 92% marks in Science stream with Physics, Chemistry, and Mathematics.",
    marks: "92%",
    status: "2024",
  },
  {
    id: 3,
    degree: "Secondary School, General Education",
    school: "Sadiya Govt HS School",
    period: "Jan 2017 - Jan 2022",
    description: "Completed my secondary education with 94.67% marks. Developed foundational knowledge in all subjects.",
    marks: "94.67%",
    status: "2022",
  },
];